{{- if .Values.cloudmapper.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudmapper-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cloudmapper.persistenceSize | default "10Gi" }}
  storageClassName: {{ .Values.cloudmapper.storageClass | default "local-path" }}
{{- end }}
