-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- Adds the 'biomcp' computing-unit type. A BioMCP session is a per-user pod
-- running docker.io/acaciaresearch/biomcp:latest, pinned at 2 CPU / 4 GiB RAM,
-- with the user-supplied WEB_APP_TOKEN injected as an env var and also kept in
-- the workflow_computing_unit.resource JSON so the user can reveal it later.
ALTER TYPE texera_db.workflow_computing_unit_type_enum ADD VALUE IF NOT EXISTS 'biomcp';
