# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

aws-ec2 {
  enabled = false
  enabled = ${?AWS_EC2_ENABLED}

  default-region = "us-east-1"
  default-region = ${?AWS_EC2_DEFAULT_REGION}

  computing-unit-port = 8085
  computing-unit-port = ${?AWS_EC2_COMPUTING_UNIT_PORT}

  # Comma-separated list, e.g. "t2.micro,t2.small,t2.medium"
  instance-type-options = "t2.micro,t2.small,t2.medium,t2.large,t2.xlarge"
  instance-type-options = ${?AWS_EC2_INSTANCE_TYPE_OPTIONS}
}
